# ---
title: "R Notebook"
output: html_notebook
---
*Ctrl+Alt+I*.
*Ctrl+Shift+K*
*Ctrl+Shift+Enter*

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(grid)
library(scales)
library(RColorBrewer)
library(tidyr)
library(vegan)
library(dendsort)
```


```{r}
inputData <- read.csv('/home/ayushi/Desktop/subspace-search/auto-mpg-7d.csv', quote="\"", header = TRUE)
#inputData <-inputData[1:10,]
vars <- inputData[c('mpg','cylinders')]
adatalabel = inputData['origin']
cnum = nrow(unique(adatalabel))
```

```{r}
x <- dist(vars, method = "euclidean", diag = TRUE, upper=TRUE)
```

```{r}
library("cluster")
library("factoextra")
library("magrittr")
library('FNN')
res.dist <- get_dist(vars, stand = TRUE, method = "euclidean")
t <- get.knn(vars, k=5)
y=t['nn.index'][1]
fviz_dist(x, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r}
t$nn.index
mat <- matrix(,nrow=nrow(inputData),ncol=nrow(inputData))
for( i in 1:nrow(inputData)) {
  for (j in 1:nrow(inputData)) {
    if(j %in% t$nn.index[i,]) {
      mat[i,j]=0
    }
    else mat[i,j]=1
  }
}
mat
rotate <- function(x) t(apply(x, 2, rev))
jpeg(file='temp.jpeg')
image(rotate(mat))
dev.off()

#par(mar=c(0, 0, 0, 0))
#image(mat, useRaster=TRUE, axes=FALSE)
#fviz_dist(mat, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r}
#t$nn.index
```

```{r}
library('seriation')
# NOT RUN {
## show available seriation methods (for dist and matrix)
#show_seriation_methods("dist")
#show_seriation_methods("matrix")

##seriate dist
data("iris")
x <- as.matrix(iris[-5])
x <- x[sample(1:nrow(x)),]
d <- dist(x)

## default seriation
order <- seriate(d)
order

## plot
pimage(d, main = "Random")
pimage(d, order, main = "Reordered")

## compare quality
rbind(
        random = criterion(d),
        reordered = criterion(d, order)
     )

## seriate matrix
data("iris")
x <- as.matrix(iris[-5])

## to make the variables comparable, we scale the data
x <- scale(x, center = FALSE)

## try some methods
pimage(x, main = "original data")
criterion(x)

order <- seriate(x, method = "BEA_TSP")
pimage(x, order, main = "TSP to optimize ME")
criterion(x, order)

order <- seriate(x, method = "PCA")
pimage(x, order, main = "First principal component")
criterion(x, order)

## 2 TSPs
order <- c(
    seriate(dist(x), method = "TSP"),
    seriate(dist(t(x)), method = "TSP")
)
pimage(x, order, main = "2 TSPs")
criterion(x, order)
# }
```


